In [206]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# handwriting number recognition

mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [207]:
x = mnist.test.labels

In [208]:
y = mnist.test.images

In [209]:
y

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [137]:
x

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [211]:
x = mnist.train.next_batch(10)

In [213]:
x

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]))

In [63]:
import numpy as np
import scipy.misc as smp


def show_img_2D(img, max_row, max_col):
    data = np.zeros((max_row, max_col, 3), dtype=np.uint8)
    row = 0
    col = 0
    for r in img:
        for i in r:
            data[row, col] = [255*i, 255*i, 255*i]
            col += 1
            if col == max_col:
                row += 1
                col = 0
    img = smp.toimage( data )       # Create a PIL image
    img.show()                      # View in default viewer

    
def show_img_1D(img, max_row, max_col):
    img_data = np.zeros((max_row, max_col, 3), dtype=np.uint8)
    row = 0
    col = 0
    
    for i in img:
        img_data[row, col] = [255*i, 255*i, 255*i]
        col += 1
        if col == max_col:
            row += 1
            col = 0
    img = smp.toimage( img_data )       # Create a PIL image
    img.show()                      # View in default viewer

In [97]:
import cv2

In [98]:
cap = cv2.VideoCapture(0)

In [99]:
ret, img = cap.read()
img = cv2.resize(img, (300, 200))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [112]:
result = []
for i in gray:
    for r in i:
        result.append(r/255.0)
filename = 'TensorPractice/training_data/top_left/%s.csv' % '1'
x = np.asarray(result)
print len(x)
x.tofile(filename,sep=',',format='%10.10f')


60000


In [9]:
import csv
import numpy as np
from itertools import imap

In [167]:
with open('training_data/top_left/1.csv') as f:
    reader = csv.reader(f)
    data = reader.next()

In [168]:
x = np.asarray(list(imap(float, data)))

In [169]:
xx = list(imap(float, data))

In [170]:
x = np.asarray(xx)

In [171]:
len(x)

60000

In [172]:
img = []
for i in range(200):
    img.append([])
    for j in range(300*i, 300*i+300):
        try:
            img[i].append(float(data[j]))
        except Exception as e:
            print i
            print j
            raise e

In [173]:
from skimage.measure import block_reduce

In [174]:
img = np.asarray(img)

In [175]:
img_reduce = block_reduce(img, block_size=(6, 6), func=np.mean)

In [176]:
len(img_reduce)

34

In [177]:
show_img_2D(img_reduce, 34, 50)

In [180]:
show_img_2D(img, 200, 300)

In [190]:
img_reduce.flatten()

array([ 0.02854031,  0.34814815,  0.75740741, ...,  0.18093682,
        0.17472767,  0.16949891])

In [204]:
data = np.asarray([1.0, 0.0, 0.0, 0.0])

In [205]:
data

array([ 1.,  0.,  0.,  0.])

In [200]:
a = np.array([])